# Site Settings
encoding: UTF-8
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor"]
lang: en # Language code as defined in _data/i18n.yml. en, en-gb, en-us, zh, zh-cn, zh-tw etc.
permalink: /blog/:year/:month/:day/:title/

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3

sass:
  style: compressed

# Site Data
url: # the base hostname & protocol for your site, e.g. http://example.com
baseurl: # the subpath of your site, e.g. /blog
title: Serendipity
description: "Zhang Chi's Portfolio"
keywords: 'research, design'
author:
  name: Zhang Chi Carol
  job_title: Student
  location: Harbin
  email: zhangchicaol@outlook.com
  social_links:
    - name: github
      url: https://github.com/zhangchicarol/zhangchicarol.github.io
    - name: linkedin
      url: https://www.linkedin.com/in/zhangchicarol/
home:
  section1: <h2>Serendipity</h2>
  section2: <h4>Zhang Chi's Portfolio</h4>
 
blog:
  cc_license: http://creativecommons.org/licenses/by-sa/4.0/ # A link to CC License of your choice.
  cc_license_image: /assets/images/theme/cc-by-sa.png # An image of your CC License. 
  footer_content: A trial explanation of serendipity <a href="http://zhangchicarol.com/"></a> .



paths:
  home: /
  blog: /blog/
  categories: /blog/categories/
  tags: /blog/tags/
